### ISSUE TITLE
Modrinth (Fabric) Availibility

### ISSUE THREAD

**Issue by ihymyly** [Sindarin27/farsighted-mobs-forge#8] opened 2024-07-30 09:02 UTC
Would it be possible for Fabric versions of this mod to be available on Modrinth? I was hoping for a 1.20.1 Fabric version, but couldn't find one (works fine on CurseForge).

**Comment by Sindarin27** [comment] 2024-10-23 15:33
Duplicate of https://github.com/Sindarin27/farsighted-mobs-fabric/issues/9

**Closed as completed by Sindarin27** 2024-10-23 15:33 UTC
